version : '3.3'

services :
    web:
        image: nginx:alpine
        volumes:
            - /share/src/statec/mailing/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - appnet
        depends_on:
            - app

    app:
        image: apimailing:latest
        container_name: mailing
        env_file:
            - .env
        volumes:
            - /share/src/statec/mailing/:/app/mailing/
        command: /bin/sh -c "/app/mailing/start.sh"
        expose:
            - 5050
        networks:
            - appnet
        
   
networks:
  appnet: